# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'HelloSayer']

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# Cell
class HelloSayer:
    "Say hello to `to` using `say_hello`"
    def __init__(self, to):
        "Define the object of the prospective saying"
        self.to = to

    def __repr__(self):
        "Represent instances for debugging"
        repr = "to: %s" % (self.to)
        return repr

    def __str__(self):
        "Represent instances when printed (see https://stackoverflow.com/a/49282111/446907)"
        return  str(self.__class__) + '\n' + '\n'.join((str(item) + ' = ' + str(self.__dict__[item]) for item in sorted(self.__dict__)))

    def say(self):
        "Do the saying"
        return say_hello(self.to)